image: python:3.10

stages:
  - "test"

before_script:
  - python -V  # Imprimer la version de python pour le d√©bogage
  - python -m pip install --upgrade pip
  - pip install --no-cache-dir -r requirements.txt -vvv

test:
  stage: test
  script:
    - python -m unittest discover